# Generated by Django 3.2.8 on 2021-10-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chest_size',
            field=models.IntegerField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='shoe_size',
            field=models.IntegerField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='waist_size',
            field=models.IntegerField(max_length=2, null=True),
        ),
    ]
