# Generated by Django 3.2.8 on 2021-10-22 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211022_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='chest_size',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shoe_size',
        ),
        migrations.RemoveField(
            model_name='user',
            name='waist_size',
        ),
    ]
