# Generated by Django 3.2.8 on 2021-10-23 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211022_0731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='city',
            new_name='apartment',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='state',
            new_name='estate',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='phone_no',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='zipcode',
            new_name='town',
        ),
    ]
