# Generated by Django 3.2.8 on 2021-10-18 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import products.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quant', models.PositiveIntegerField(default=0)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uqid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('brand', models.CharField(choices=[('network', 'Network'), ('mufti', 'Mufti'), ('anthem', 'Anthem'), ('blue saint', 'Blue Saint'), ('dennis lingo', 'Dennis Lingo'), ('balista', 'Balista'), ('hue', 'Hue'), ('harbour', 'Harbour'), ('flyrs', 'Flyrs'), ('up', 'UP')], max_length=70)),
                ('name', models.CharField(max_length=150)),
                ('img1', models.ImageField(upload_to=products.models.path_and_rename)),
                ('img2', models.ImageField(blank=True, null=True, upload_to=products.models.path_and_rename)),
                ('img3', models.ImageField(blank=True, null=True, upload_to=products.models.path_and_rename)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField(default=products.models.get_fake_description)),
                ('category', models.IntegerField(choices=[(1, 'Shirts'), (2, 'Tshirts'), (3, 'Sweatshirts'), (4, 'Jackets'), (5, 'Tanktops'), (6, 'Blazers'), (7, 'Dress'), (8, 'Jeans'), (9, 'Shorts'), (10, 'Track Pants'), (11, 'Trousers')])),
                ('composition', models.CharField(default='100% Cotton', max_length=120)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=15)),
                ('sm_quant', models.PositiveIntegerField(default=0)),
                ('m_quant', models.PositiveIntegerField(default=0)),
                ('l_quant', models.PositiveIntegerField(default=0)),
                ('xl_quant', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_quant', models.PositiveIntegerField()),
                ('total_price', models.PositiveIntegerField()),
                ('shipping_cost', models.PositiveIntegerField()),
                ('payment_status', models.PositiveIntegerField(blank=True, choices=[(1, 'pending'), (2, 'success'), (3, 'failed')], default=1)),
                ('status', models.PositiveIntegerField(blank=True, choices=[(1, 'waiting confirmation'), (2, 'confirmed'), (3, 'processed'), (4, 'shipped'), (5, 'delivered'), (6, 'cancelled')], default=1)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=500, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=500, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=500, null=True)),
                ('shipping_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.address')),
                ('user', models.ForeignKey(on_delete=models.SET(products.models.get_sentinel_user), related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('sm', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL')], max_length=5)),
                ('quant', models.PositiveSmallIntegerField()),
                ('item_price', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.orders')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
            options={
                'unique_together': {('order', 'product', 'size')},
            },
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('sm', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL')], max_length=5)),
                ('quant', models.PositiveSmallIntegerField(null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'unique_together': {('cart', 'product', 'size')},
            },
        ),
    ]
