# Generated by Django 3.2.8 on 2021-10-25 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import products.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_auto_20211023_0655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quant', models.PositiveIntegerField(default=0)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_quant', models.PositiveIntegerField()),
                ('total_price', models.PositiveIntegerField()),
                ('shipping_cost', models.PositiveIntegerField()),
                ('payment_status', models.PositiveIntegerField(blank=True, choices=[(1, 'pending'), (2, 'success'), (3, 'failed')], default=1)),
                ('status', models.PositiveIntegerField(blank=True, choices=[(1, 'waiting confirmation'), (2, 'confirmed'), (3, 'processed'), (4, 'shipped'), (5, 'delivered'), (6, 'cancelled')], default=1)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('shipping_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.address')),
                ('user', models.ForeignKey(on_delete=models.SET(products.models.get_sentinel_user), related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uqid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('brand', models.CharField(blank=True, choices=[('nike', 'Nike'), ('fendi', 'Fendi'), ('zara', 'Zara'), ('dior', 'Dior'), ('versace', 'Versace'), ('chanel', 'Chanel'), ('prada', 'Prada'), ('louis vuitton', 'Louis Vuitton'), ('adidas', 'Adidas'), ('burberry', 'Burberry')], max_length=70, null=True)),
                ('name', models.CharField(max_length=150)),
                ('img1', models.ImageField(upload_to=products.models.path_and_rename)),
                ('img2', models.ImageField(blank=True, null=True, upload_to=products.models.path_and_rename)),
                ('img3', models.ImageField(blank=True, null=True, upload_to=products.models.path_and_rename)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('category', models.IntegerField(blank=True, choices=[(1, 'Shirts'), (2, 'Tshirts'), (3, 'Sweatshirts'), (4, 'Jackets'), (5, 'Tanktops'), (6, 'Blazers'), (7, 'Dress'), (8, 'Jeans'), (9, 'Shorts'), (10, 'Track Pants'), (11, 'Trousers'), (15, 'Heels'), (16, 'Sneaker'), (17, 'Boots'), (18, 'Sandals'), (12, 'Watches'), (13, 'Bags'), (14, 'lingerie')], null=True)),
                ('composition', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('clothes', 'clothes'), ('watches', 'watches'), ('shoes', 'shoes'), ('lingerie', 'lingerie'), ('bags', 'bags')], max_length=15)),
                ('sm_quant', models.PositiveIntegerField(default=0)),
                ('m_quant', models.PositiveIntegerField(default=0)),
                ('l_quant', models.PositiveIntegerField(default=0)),
                ('xl_quant', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('xsm', 'XSM/36'), ('sm', 'S/37'), ('m', 'M/38'), ('l', 'L/39'), ('xl', 'XL/40'), ('xxl', 'XXL/41')], default='XSM', max_length=5)),
                ('quant', models.PositiveSmallIntegerField()),
                ('item_price', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
            options={
                'unique_together': {('order', 'product', 'size')},
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('xsm', 'XSM/36'), ('sm', 'S/37'), ('m', 'M/38'), ('l', 'L/39'), ('xl', 'XL/40'), ('xxl', 'XXL/41')], default='XSM', max_length=5)),
                ('quant', models.PositiveSmallIntegerField(null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'unique_together': {('cart', 'product', 'size')},
            },
        ),
    ]
