# Generated by Django 3.2.8 on 2021-10-18 12:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItems',
            new_name='CartItem',
        ),
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='OrderItems',
            new_name='OrderItem',
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('network', 'Network'), ('mufti', 'Mufti'), ('anthem', 'Anthem'), ('blue saint', 'Blue Saint'), ('dennis lingo', 'Dennis Lingo'), ('balista', 'Balista'), ('hue', 'Hue'), ('harbour', 'Harbour'), ('flyrs', 'Flyrs'), ('up', 'UP')], max_length=70, null=True),
        ),
    ]
