# Generated by Django 3.2.8 on 2021-10-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211018_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gender',
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('clothes', 'clothes'), ('watches', 'watches'), ('shoes', 'shoes'), ('lingerie', 'lingerie')], default='watches', max_length=15),
            preserve_default=False,
        ),
    ]
