# Generated by Django 3.2.8 on 2021-10-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211018_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Shirts'), (2, 'Tshirts'), (3, 'Sweatshirts'), (4, 'Jackets'), (5, 'Tanktops'), (6, 'Blazers'), (7, 'Dress'), (8, 'Jeans'), (9, 'Shorts'), (10, 'Track Pants'), (11, 'Trousers')], null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='composition',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('clothes', 'clothes'), ('watches', 'watches'), ('shoes', 'shoes'), ('lingerie', 'lingerie'), ('beauty', 'beauty')], max_length=15),
        ),
    ]
