# Generated by Django 3.2.8 on 2021-10-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20211018_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(choices=[('xsm', 'XSM'), ('sm', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL')], default='XSM', max_length=5),
        ),
    ]
