# Generated by Django 3.2.8 on 2021-10-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20211020_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('clothes', 'clothes'), ('watches', 'watches'), ('shoes', 'shoes'), ('lingerie', 'lingerie'), ('bags', 'bags')], max_length=15),
        ),
    ]
